"""pass
Revision ID: 191b9cabe724
Revises: 84dec5e343ff
Create Date: 2025-07-03 17:08:00.909505+00:00
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '191b9cabe724'
down_revision = '84dec5e343ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('site_config', 'insert_dt',
                    existing_type=postgresql.TIMESTAMP(),
                    server_default=sa.text("timezone(current_setting('TIMEZONE'), clock_timestamp())"),
                    existing_comment='Дата вставки',
                    existing_nullable=False,
                    schema='common')
    op.alter_column('address_user', 'update_dt',
                    existing_type=postgresql.TIMESTAMP(),
                    server_default=sa.text("timezone(current_setting('TIMEZONE'), clock_timestamp())"),
                    existing_comment='Дата изменения',
                    existing_nullable=False,
                    schema='data')
    op.alter_column('address_user', 'insert_dt',
                    existing_type=postgresql.TIMESTAMP(),
                    server_default=sa.text("timezone(current_setting('TIMEZONE'), clock_timestamp())"),
                    existing_comment='Дата вставки',
                    existing_nullable=False,
                    schema='data')
    op.alter_column('site_content', 'update_dt',
                    existing_type=postgresql.TIMESTAMP(),
                    server_default=sa.text("timezone(current_setting('TIMEZONE'), clock_timestamp())"),
                    existing_comment='Дата изменения',
                    existing_nullable=False,
                    schema='data')
    op.alter_column('site_content', 'insert_dt',
                    existing_type=postgresql.TIMESTAMP(),
                    server_default=sa.text("timezone(current_setting('TIMEZONE'), clock_timestamp())"),
                    existing_comment='Дата вставки',
                    existing_nullable=False,
                    schema='data')
    op.alter_column('site_map', 'update_dt',
                    existing_type=postgresql.TIMESTAMP(),
                    server_default=sa.text("timezone(current_setting('TIMEZONE'), clock_timestamp())"),
                    existing_comment='Дата изменения',
                    existing_nullable=False,
                    schema='data')
    op.alter_column('site_map', 'insert_dt',
                    existing_type=postgresql.TIMESTAMP(),
                    server_default=sa.text("timezone(current_setting('TIMEZONE'), clock_timestamp())"),
                    existing_comment='Дата вставки',
                    existing_nullable=False,
                    schema='data')
    op.alter_column('subdomains', 'update_dt',
                    existing_type=postgresql.TIMESTAMP(),
                    server_default=sa.text("timezone(current_setting('TIMEZONE'), clock_timestamp())"),
                    existing_comment='Дата изменения',
                    existing_nullable=False,
                    schema='data')
    op.alter_column('subdomains', 'insert_dt',
                    existing_type=postgresql.TIMESTAMP(),
                    server_default=sa.text("timezone(current_setting('TIMEZONE'), clock_timestamp())"),
                    existing_comment='Дата вставки',
                    existing_nullable=False,
                    schema='data')
    op.alter_column('user_account', 'update_dt',
                    existing_type=postgresql.TIMESTAMP(),
                    server_default=sa.text("timezone(current_setting('TIMEZONE'), clock_timestamp())"),
                    existing_comment='Дата изменения',
                    existing_nullable=False,
                    schema='data')
    op.alter_column('user_account', 'insert_dt',
                    existing_type=postgresql.TIMESTAMP(),
                    server_default=sa.text("timezone(current_setting('TIMEZONE'), clock_timestamp())"),
                    existing_comment='Дата вставки',
                    existing_nullable=False,
                    schema='data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_account', 'insert_dt',
                    existing_type=postgresql.TIMESTAMP(),
                    server_default=sa.text("timezone(current_setting('TIMEZONE'::text), clock_timestamp())"),
                    existing_comment='Дата вставки',
                    existing_nullable=False,
                    schema='data')
    op.alter_column('user_account', 'update_dt',
                    existing_type=postgresql.TIMESTAMP(),
                    server_default=sa.text("timezone(current_setting('TIMEZONE'::text), clock_timestamp())"),
                    existing_comment='Дата изменения',
                    existing_nullable=False,
                    schema='data')
    op.alter_column('subdomains', 'insert_dt',
                    existing_type=postgresql.TIMESTAMP(),
                    server_default=sa.text("timezone(current_setting('TIMEZONE'::text), clock_timestamp())"),
                    existing_comment='Дата вставки',
                    existing_nullable=False,
                    schema='data')
    op.alter_column('subdomains', 'update_dt',
                    existing_type=postgresql.TIMESTAMP(),
                    server_default=sa.text("timezone(current_setting('TIMEZONE'::text), clock_timestamp())"),
                    existing_comment='Дата изменения',
                    existing_nullable=False,
                    schema='data')
    op.alter_column('site_map', 'insert_dt',
                    existing_type=postgresql.TIMESTAMP(),
                    server_default=sa.text("timezone(current_setting('TIMEZONE'::text), clock_timestamp())"),
                    existing_comment='Дата вставки',
                    existing_nullable=False,
                    schema='data')
    op.alter_column('site_map', 'update_dt',
                    existing_type=postgresql.TIMESTAMP(),
                    server_default=sa.text("timezone(current_setting('TIMEZONE'::text), clock_timestamp())"),
                    existing_comment='Дата изменения',
                    existing_nullable=False,
                    schema='data')
    op.alter_column('site_content', 'insert_dt',
                    existing_type=postgresql.TIMESTAMP(),
                    server_default=sa.text("timezone(current_setting('TIMEZONE'::text), clock_timestamp())"),
                    existing_comment='Дата вставки',
                    existing_nullable=False,
                    schema='data')
    op.alter_column('site_content', 'update_dt',
                    existing_type=postgresql.TIMESTAMP(),
                    server_default=sa.text("timezone(current_setting('TIMEZONE'::text), clock_timestamp())"),
                    existing_comment='Дата изменения',
                    existing_nullable=False,
                    schema='data')
    op.alter_column('address_user', 'insert_dt',
                    existing_type=postgresql.TIMESTAMP(),
                    server_default=sa.text("timezone(current_setting('TIMEZONE'::text), clock_timestamp())"),
                    existing_comment='Дата вставки',
                    existing_nullable=False,
                    schema='data')
    op.alter_column('address_user', 'update_dt',
                    existing_type=postgresql.TIMESTAMP(),
                    server_default=sa.text("timezone(current_setting('TIMEZONE'::text), clock_timestamp())"),
                    existing_comment='Дата изменения',
                    existing_nullable=False,
                    schema='data')
    op.alter_column('site_config', 'insert_dt',
                    existing_type=postgresql.TIMESTAMP(),
                    server_default=sa.text("timezone(current_setting('TIMEZONE'::text), clock_timestamp())"),
                    existing_comment='Дата вставки',
                    existing_nullable=False,
                    schema='common')
    # ### end Alembic commands ###
