"""first_tables

Revision ID: 84dec5e343ff
Revises: 1
Create Date: 2025-06-29 07:08:23.487992+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '84dec5e343ff'
down_revision = '1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE IF EXISTS value_data_type")
    op.execute("DROP TYPE IF EXISTS html_document_type")
    op.execute("DROP TYPE IF EXISTS content_type")

    op.create_table('site_config',
                    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False,
                              comment='Идентификатор site_config'),
                    sa.Column('key', sa.String(length=30), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=True),
                    sa.Column('value', sa.String(), nullable=False),
                    sa.Column('value_type',
                              sa.Enum('float', 'string', 'integer', 'boolean', 'datetype', name='value_data_type',
                                      create_constraint=True), nullable=False),
                    sa.Column('insert_dt', sa.DateTime(),
                              server_default=sa.text("timezone(current_setting('TIMEZONE'), clock_timestamp())"),
                              nullable=False, comment='Дата вставки'),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_site_config')),
                    schema='common',
                    comment='Параметры конфигурации сайта',
                    info={'title': 'Параметры конфигурации сайта'}
                    )
    op.create_table('geo_objects',
                    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False,
                              comment='Идентификатор geo_objects'),
                    sa.Column('name', sa.String(length=255), nullable=False, comment='Наименование объекта'),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_geo_objects')),
                    schema='data',
                    comment='География'
                    )
    op.create_table('user_account',
                    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False,
                              comment='Идентификатор user_account'),
                    sa.Column('name', sa.String(length=30), nullable=False),
                    sa.Column('full_name', sa.String(), nullable=True),
                    sa.Column('update_dt', sa.DateTime(),
                              server_default=sa.text("timezone(current_setting('TIMEZONE'), clock_timestamp())"),
                              nullable=False, comment='Дата изменения'),
                    sa.Column('insert_dt', sa.DateTime(),
                              server_default=sa.text("timezone(current_setting('TIMEZONE'), clock_timestamp())"),
                              nullable=False, comment='Дата вставки'),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_account')),
                    schema='data',
                    comment='Пользователи',
                    info={'title': 'Пользователи'}
                    )
    op.create_table('address_user',
                    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False,
                              comment='Идентификатор address_user'),
                    sa.Column('email_address', sa.String(), nullable=False),
                    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='ID пользователя'),
                    sa.Column('address', sa.String(), nullable=True),
                    sa.Column('phone', sa.Integer(), nullable=True),
                    sa.Column('geo', sa.BigInteger(), nullable=True, comment='Координаты'),
                    sa.Column('update_dt', sa.DateTime(),
                              server_default=sa.text("timezone(current_setting('TIMEZONE'), clock_timestamp())"),
                              nullable=False, comment='Дата изменения'),
                    sa.Column('insert_dt', sa.DateTime(),
                              server_default=sa.text("timezone(current_setting('TIMEZONE'), clock_timestamp())"),
                              nullable=False, comment='Дата вставки'),
                    sa.ForeignKeyConstraint(['geo'], ['data.geo_objects.id'],
                                            name=op.f('fk_address_user_geo_geo_objects')),
                    sa.ForeignKeyConstraint(['user_id'], ['data.user_account.id'],
                                            name=op.f('fk_address_user_user_id_user_account')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_address_user')),
                    schema='data',
                    comment='Адрес пользователя',
                    info={'title': 'Пользователи'}
                    )
    op.create_table('subdomains',
                    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False,
                              comment='Идентификатор subdomains'),
                    sa.Column('name', sa.String(length=127), nullable=False),
                    sa.Column('description', sa.String(length=127), nullable=True),
                    sa.Column('geo', sa.BigInteger(), nullable=True, comment='Координаты'),
                    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('update_dt', sa.DateTime(),
                              server_default=sa.text("timezone(current_setting('TIMEZONE'), clock_timestamp())"),
                              nullable=False, comment='Дата изменения'),
                    sa.Column('insert_dt', sa.DateTime(),
                              server_default=sa.text("timezone(current_setting('TIMEZONE'), clock_timestamp())"),
                              nullable=False, comment='Дата вставки'),
                    sa.ForeignKeyConstraint(['geo'], ['data.geo_objects.id'],
                                            name=op.f('fk_subdomains_geo_geo_objects')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_subdomains')),
                    schema='data',
                    comment='Карта сайта',
                    info={'title': 'Карта сайта'}
                    )
    op.create_table('site_map',
                    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False,
                              comment='Идентификатор site_map'),
                    sa.Column('subdomain_id', sa.BigInteger(), nullable=False),
                    sa.Column('path', sa.String(length=255), nullable=False),
                    sa.Column('name', sa.String(length=127), nullable=False),
                    sa.Column('doc_type',
                              sa.Enum('plain', 'article', 'category', 'items', 'service', name='html_document_type',
                                      create_constraint=True), nullable=False),
                    sa.Column('sort_order', sa.Integer(), nullable=False, comment='Порядок сортировки'),
                    sa.Column('services', postgresql.ARRAY(sa.String()), nullable=True),
                    sa.Column('relevance', postgresql.ARRAY(sa.String()), nullable=True),
                    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('parent_id', sa.BigInteger(), nullable=False, comment='Идентификатор родителя'),
                    sa.Column('is_view', sa.Boolean(), nullable=False, comment='Признак видимости'),
                    sa.Column('update_dt', sa.DateTime(),
                              server_default=sa.text("timezone(current_setting('TIMEZONE'), clock_timestamp())"),
                              nullable=False, comment='Дата изменения'),
                    sa.Column('insert_dt', sa.DateTime(),
                              server_default=sa.text("timezone(current_setting('TIMEZONE'), clock_timestamp())"),
                              nullable=False, comment='Дата вставки'),
                    sa.ForeignKeyConstraint(['subdomain_id'], ['data.subdomains.id'],
                                            name=op.f('fk_site_map_subdomain_id_subdomains')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_site_map')),
                    schema='data',
                    comment='Карта сайта',
                    info={'title': 'Карта сайта'}
                    )

    op.create_index(
        op.f('ix_data_site_map_is_view'), 'site_map', ['is_view'], schema='data'
    )
    op.create_index(
        op.f('ix_data_site_map_parent_id'), 'site_map', ['parent_id'], schema='data'
    )
    op.create_index(
        op.f('ix_data_site_map_sort_order'), 'site_map', ['sort_order'], schema='data'
    )
    op.create_table('site_content',
                    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False,
                              comment='Идентификатор site_content'),
                    sa.Column(
                        'document_id', sa.BigInteger(), nullable=False, comment='Идентификатор документа'
                    ),
                    sa.Column('content', sa.String(), nullable=False),
                    sa.Column('content_type',
                              sa.Enum('html', 'slider', 'gallery', 'image', 'media', 'html_form', 'map',
                                      name='content_type', create_constraint=True), nullable=False),
                    sa.Column('update_dt', sa.DateTime(),
                              server_default=sa.text("timezone(current_setting('TIMEZONE'), clock_timestamp())"),
                              nullable=False, comment='Дата изменения'),
                    sa.Column('insert_dt', sa.DateTime(),
                              server_default=sa.text("timezone(current_setting('TIMEZONE'), clock_timestamp())"),
                              nullable=False, comment='Дата вставки'),
                    sa.ForeignKeyConstraint(['document_id'], ['data.site_map.id'],
                                            name=op.f('fk_site_content_document_id_site_map')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_site_content')),
                    schema='data',
                    comment='Контент документа'
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_content', schema='data')
    op.drop_index(op.f('ix_data_site_map_sort_order'), table_name='site_map', schema='data')
    op.drop_index(op.f('ix_data_site_map_parent_id'), table_name='site_map', schema='data')
    op.drop_index(op.f('ix_data_site_map_is_view'), table_name='site_map', schema='data')
    op.drop_table('site_map', schema='data')
    op.drop_table('subdomains', schema='data')
    op.drop_table('address_user', schema='data')
    op.drop_table('user_account', schema='data')
    op.drop_table('geo_objects', schema='data')
    op.drop_table('site_config', schema='common')
    op.execute("DROP TYPE IF EXISTS value_data_type")
    op.execute("DROP TYPE IF EXISTS html_document_type")
    op.execute("DROP TYPE IF EXISTS content_type")
    # ### end Alembic commands ###
